
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    ports:
      - "5433:5432"  # Fix: added space and quotes
    environment:
      POSTGRES_USER: adminHu101
      POSTGRES_PASSWORD: pass101
      POSTGRES_DB: notes
    volumes:
      - notesData:/var/lib/postgresql/data



volumes:
  notesData:
